Bumped version to 2.1.6
divio/aldryn-django pull request #141
Opened 2019-02-11 13:10 UTC by FinalAngel

* Upgrade Django to 2.1.6 (fixes CVE-2019-6975)
  see https://www.djangoproject.com/weblog/2019/feb/11/security-releases/
  for details

2019-02-11 14:32 UTC, FinalAngel commented
Waiting for https://code.djangoproject.com/ticket/30175 to be resolved

2019-02-11 16:33 UTC, vThaian commented
Let's keep the same format as earlier:
Bumped version to 1.11.18.2 (#138)

2019-02-11 16:33 UTC, bplociennik approved these changes

2019-02-12 02:55 UTC, evildmp requested changes

2019-02-12 02:55 UTC, evildmp commented on CHANGELOG.rst
> +* Django 2.1.6 was faulty and skipped, see
``was faulty and is not provided on Divio Cloud``

2019-02-12 08:26 UTC, merged